CREATE TABLE EMPLOYEE(
 ID INT PRIMARY KEY,
 NAME VARCHAR(100),
 DEPARTMENT VARCHAR(50),
 SALARY INT,
 CITY VARCHAR(50)
);

CREATE TABLE LOAN(
 LOAN_ID INT PRIMARY KEY,
 CUSTOMER_NAME VARCHAR(100),
 AMOUNT INT,
 STATUS VARCHAR(20)
);