CREATE TABLE EMPLOYEE(
 ID INT PRIMARY KEY,
 NAME VARCHAR(100),
 DEPARTMENT VARCHAR(50),
 SALARY INT,
 CITY VARCHAR(50)
);

CREATE TABLE LOAN(
 LOAN_ID INT PRIMARY KEY,
 EMPLOYEE_ID INT,
 AMOUNT INT,
 STATUS VARCHAR(20),
 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

CREATE INDEX idx_name ON EMPLOYEE (NAME);
CREATE INDEX idx_emp_id ON LOAN (EMPLOYEE_ID);
CREATE INDEX idx_emp_city ON EMPLOYEE ( CITY );
